name: Example Test - CI Framework Test for Xray with Cypress and GitHub Actions

on:
    workflow_dispatch:
        inputs:
            test_execution_key:
                description: 'https://dashboard.cypress.io/invitation/72fff246-cd4a-442e-8952-15b4b74a7872'
                required: false
                default: ''

jobs:
    in-sprint_test_US-GX-5_GitHub_Integration_for_Xray:
        runs-on: ubuntu-latest
        steps:
            - name: Github Actions
              uses: actions/checkout@v3

            - name: Cypress Run
              uses: cypress-io/github-action@v4.1.1
              with:
                  browser: chrome
                  spec: cypress/e2e/cucumber-test/Test-Suite-example/GX-2-LoginTest.feature
                  record: true
              env:
                  CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
                  GITHUB_TOKEN: ${{secrets.ELY_GITHUB_TOKEN}}
                  CYPRESS_PROJECT_ID: ${{secrets.CYPRESS_PROJECT_ID}}

            - name: xray-action
            - name: Get Xray Cloud API token
              env:
                CLIENT_ID: ${{secrets.XRAY_CLIENT_ID}}
                CLIENT_SECRET: ${{secrets.XRAY_CLIENT_SECRET}}
              id: xray-token
              run: |
                echo ::set-output name=XRAY_TOKEN::$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$CLIENT_ID\",\"client_secret\": \"$CLIENT_SECRET\" }" https://xray.cloud.getxray.app/api/v1/authenticate| tr -d '"')
            - name: Submit results to Xray
              run: 'curl -H "Content-Type: text/xml" -H "Authorization: Bearer ${{ steps.xray-token.outputs.XRAY_TOKEN }}" --data @cypress/test-reports/*.xml  "https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=GX&testExecKey=GX-5"'